### ISSUE TITLE
fix the size using resize on display

### ISSUE THREAD

**Issue by kyakan** [niedzielski/git-diff-img#1]
Thanks for sharing that, could make sense to add the `-resize 1900x` or prefered size to avoid overflow in the screen for big images:

https://github.com/niedzielski/git-diff-img/blob/9eab4dc677879bd34d32120397adc1196813022a/git-diff-img#L6

like adding:

```bash
   display -resize 1900x -title "$BASE: Local | Diff | Remote" png:- 
```

**Comment by niedzielski** [comment]
@kyakan, sounds useful! I'm on Debian stable which has ImageMagick v6.9.11-60 and it doesn't seem to support [the `-resize` argument](https://imagemagick.org/script/command-line-options.php#resize) yet so I can't easily play with it. Most of my own usages these days are for pixel art which I don't want resized but there are many images I would love to be resized. I'm guessing that would require some fiddling though so I've added a tip to the readme for now. Thank you!
